### ISSUE TITLE
Multi-node cluster deployment: Node 3 doesn't always start successfully

### ISSUE THREAD

**Issue by ozskywalker** [ozskywalker/docker-fusion#4]
(Is this a load issue on a single node?  Devise test & run on larger deployment [AWS, digitalocean, etc.])

During "big bang" cluster startup (docker-compose -d up), node3 sometimes does not always come online and requires a container-level stop & start.

![image](https://cloud.githubusercontent.com/assets/5518808/26034103/380ab28c-3885-11e7-96c0-1b1530bb7800.png)

**Comment by ozskywalker** [comment]
Can also manifest itself such as below:

```node3    | 2017-05-14 13:09:29,665 [myid:] - INFO  [main:QuorumPeerConfig@114] - Reading configuration from: /tmp/zookeeper/bin/../conf/zoo.cfg
node3    | 2017-05-14 13:09:29,683 [myid:] - INFO  [main:QuorumPeerConfig@316] - clientPortAddress is 0.0.0.0/0.0.0.0:2181
node3    | 2017-05-14 13:09:29,684 [myid:] - INFO  [main:QuorumPeerConfig@320] - secureClientPort is not set
node3    | 2017-05-14 13:09:29,694 [myid:] - WARN  [main:QuorumPeerConfig@555] - No server failure will be tolerated. You need at least 3 servers.
node3    | 2017-05-14 13:09:29,696 [myid:3] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
node3    | 2017-05-14 13:09:29,697 [myid:3] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
node3    | 2017-05-14 13:09:29,697 [myid:3] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
node3    | 2017-05-14 13:09:29,715 [myid:3] - INFO  [main:QuorumPeerMain@136] - Starting quorum peer
node3    | 2017-05-14 13:09:29,730 [myid:3] - INFO  [main:NIOServerCnxnFactory@673] - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 8 worker threads, and 64 kB direct buffers.
node3    | 2017-05-14 13:09:29,747 [myid:3] - INFO  [main:NIOServerCnxnFactory@686] - binding to port 0.0.0.0/0.0.0.0:2181
node3    | 2017-05-14 13:09:29,800 [myid:3] - INFO  [main:Slf4jLog@67] - Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
node3    | 2017-05-14 13:09:29,848 [myid:3] - INFO  [main:QuorumPeer@1280] - Local sessions disabled
node3    | 2017-05-14 13:09:29,848 [myid:3] - INFO  [main:QuorumPeer@1291] - Local session upgrading disabled
node3    | 2017-05-14 13:09:29,848 [myid:3] - INFO  [main:QuorumPeer@1258] - tickTime set to 2000
node3    | 2017-05-14 13:09:29,848 [myid:3] - INFO  [main:QuorumPeer@1302] - minSessionTimeout set to 4000
node3    | 2017-05-14 13:09:29,848 [myid:3] - INFO  [main:QuorumPeer@1313] - maxSessionTimeout set to 40000
node3    | 2017-05-14 13:09:29,849 [myid:3] - INFO  [main:QuorumPeer@1328] - initLimit set to 10
node3    | 2017-05-14 13:09:29,861 [myid:3] - ERROR [main:QuorumPeerMain@98] - Unexpected exception, exiting abnormally
node3    | java.lang.RuntimeException: My id 3 not in the peer list
node3    | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:716)
node3    | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:183)
node3    | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:120)
node3    | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:79)
node3    | ui is not running.
node3    | connectors is not running.
node3    | api is not running.
node3    | solr is not running.```
